[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "fibby"
version = "0.0.1"
description = "a minimal example package (fortran version)"
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: BSD License",
]
dependencies = ["numpy"]

# Scikit-Build Configuration
[tool.scikit-build]
cmake.verbose = true
logging.level = "INFO"
wheel.install-dir = "pyne/core"
#wheel.packages = ["pyne"]
#wheel.exclude = ["CMakeLists.txt", "*.pyx"]
build-dir = "scikit-build"
